services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: assist
      POSTGRES_PASSWORD:
      POSTGRES_DB: assistdb
    volumes:
      - ./db/data:/var/lib/postgresql/data
      
    ports:
      - "5432:5432"
